### ISSUE TITLE
Bug report: unable to generate getter/setter correctly

### ISSUE THREAD

**Issue by doggy8088** [afmicc/getter-setter-generator#1]
See screenshot:

![untitled project](https://user-images.githubusercontent.com/88981/38301864-6942e668-3833-11e8-86a0-6b26a98b9b3e.gif)

**Comment by doanthai** [comment]
This extension may be only use for java. If you code typescript , you should use this extension: Generate https://marketplace.visualstudio.com/items?itemName=Wilson-Godoi.wg-getters-and-setters
